USE Floppy;
DELIMITER $$

DROP PROCEDURE IF EXISTS searchColony$$

CREATE PROCEDURE searchState(IN State VARCHAR(100))
    BEGIN
    	INSERT INTO FRACCIONAMIENTO(id_vig) SELECT VIGILANTE.id_vig FROM VIGILANTE INNER JOIN FRACCIONAMIENTO ON VIGILANTE.dir_vig = FRACCIONAMIENTO.dir_fra;
    END$$