USE Floppy;

DELIMITER $$
DROP PROCEDURE IF EXISTS InsertIdVig;
DROP PROCEDURE IF EXISTS ConsultarVigyFrac;

CREATE PROCEDURE InsertIdVig()
    BEGIN
		  UPDATE FRACCIONAMIENTO INNER JOIN VIGILANTE ON (VIGILANTE.dir_vig = FRACCIONAMIENTO.dir_fra) SET FRACCIONAMIENTO.id_vig = VIGILANTE.id_vig WHERE dir_fra = VIGILANTE.dir_vig;
    END$$
CREATE PROCEDURE ConsultarVigyFrac()
    BEGIN
		  SELECT VIGILANTE.nom_vig, FRACCIONAMIENTO.dir_fra FROM (FRACCIONAMIENTO INNER JOIN VIGILANTE ON (VIGILANTE.dir_vig = FRACCIONAMIENTO.dir_fra));
    END$$
